---
title: "Untitled Draft"
author: "Report Author"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Analysis

```{r}

# exploring the data

library(visdat)
library(naniar)
vis_dat(gs_football_r1, sort_type = FALSE)
vis_dat(gs_football_r2, sort_type = FALSE)
vis_dat(gs_football, sort_type = FALSE)

# check values are integers
gs_football %>% 
  select(any_missing_data_statement:was_data_shared) %>% 
  map(unique)
```

```{r}
gs_football <- readr::read_rds("data/gs-football.rds")

# calculate agreement
library(irr)

# any_missing_data_statement
# list(
#   any_missing_data_statement = identify_mismatch(gs_football,
#                                                  any_missing_data_statement),
#   any_statement_about_mcar_mnar_mar = identify_mismatch(gs_football,
#                                                         any_statement_about_mcar_mnar_mar),
#   
#   were_missing_data_explored = identify_mismatch(gs_football, were_missing_data_explored),
#   
#   was_imputation_used = identify_mismatch(gs_football, was_imputation_used),
#   
#   was_data_shared = identify_mismatch(gs_football, was_data_shared)
# ) %>%
#   bind_rows(.id = "variable") %>%
#   write_csv(path = "data/missing-data-mismatches.csv")



# Now we bring the third and final review 
gs_mismatches <- readr::read_csv("data/missing-data-mismatches.csv")

gs_mismatches %>% 
  pivot_longer(cols = c(reviewer_1,reviewer_2, third_check),
               names_to = "reviewer",
               values_to = "decision") %>% 
  pivot_wider(names_from = variable,
              values_from = decision)

gs_football %>% 
  pivot_wider(names_from = reviewer,
              values_from = )

# supp materials - agreement between Reviewer 1 and Reviewer 2



#the agreement was `r agree_var(gs_football, was_data_shared)`%

gs_football %>% 
  filter(study_eligibility) %>% 
  vis_miss(sort_miss = TRUE)

gs_football %>% 
  filter(study_eligibility) %>% 
  miss_var_summary()

# preliminary study
gs_football %>% 
  filter(study_eligibility) %>% 
  group_by(reviewer) %>% 
  count(any_missing_data_statement) 

gs_football %>% 
  filter(study_eligibility) %>% 
  group_by(reviewer) %>% 
  count(any_missing_data_statement)


library(irr)
data(video)
video

gs_football %>% 
  filter(study_eligibility) %>% 
  filter(any_missing_data_statement == "NA")


gs_football %>% 
  filter(study_eligibility) %>% 
  select(reviewer, any_missing_data_statement) %>% 
  pivot_wider(names_from = reviewer,
              values_from = any_missing_data_statement,
              values_fn = list) 


```


## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
