---
title: "Supplement 3"
output: html_document
---

```{r library}
library(tidyverse)
library(fitzRoy)
library(mice)
library(naniar)
```


```{r}
# Aim of this section:
# Simulate data from a real data set, insert missing
# Mini study: predicting super coach scores

d <- get_afltables_stats(start_date = "2020-01-01", 
                         end_date = "2020-09-04")

data <-
  d %>% select(
    ID,
    Round,
    First.name,
    Surname,
    Kicks,
    Handballs,
    Marks,
    Hit.Outs,
    Contested.Possessions,
    Uncontested.Possessions
  )
#View(data)

df <- get_footywire_stats(10286:10290) # Get the fantasy scores

# View(df)
df #%>% View("footywire dataset")
```


```{r}
# Simulate data from summarises of the above dataset
rnorm(n = 100, # N is the amount of data points being generated
      mean = 5,
      sd = 2)
sample.int(100, # numbers between 1 and 100
           10) # observations
rpois(n = 100,
      lambda = 5)
```


```{r}
# Generate the y-variable
fit <- lm(AF ~ K + HB, data = df)
summary(fit)
data %>% mutate(fanasty_score = 4.106*Kicks + 2.175*Handballs)
```


```{r}
# Completed dataset
# Drop a team
No_Richmond <- df %>% filter(Team!="Richmond")
sort(unique(No_Richmond$Team))
sort(unique(df$Team))
```


```{r}
# Impute missing values
df_first_try <- mice::ampute(data = df[,10:43])
df_first_try <- df_first_try$amp
```


```{r}
# Examples of presenting of missing values
naniar::vis_miss(df_first_try)
naniar::vis_miss(df_first_try)
naniar::gg_miss_fct(x = riskfactors, fct = marital)

# Example write up of missing values

# Things to do
# Get Nick's thoughts on what we include; and how to write it up.
# What do we drop to introduce bias, a team, a position, etc.


```


Appendix of techniques for dealing with missing values

-   scripts for exploring missingness

-   How to unpack the missingness in the paper text

```{=html}
<!-- -->
```

